### ISSUE TITLE
any plans to add DSS?

### ISSUE THREAD

**Issue by WastlM** [FK83/scoringRules#35]
I believe there was a great need for such an R package dedicated to the computation of proper scoring rules. So thanks for that, especially for also covering the major distributions for count data now.

Are there any plans to add functions for the Dawid-Sebastiani score? Of course, that score is much simpler to compute than the other scores, so one might ask whether there is an actual need for a dedicated function. I think it would nicely complement the current functionality, given that it is exactly the set of RPS, logS and DSS which I have used several times in applications with multivariate time series models for infectious disease surveillance data. The [**surveillance**](https://CRAN.R-project.org/package=surveillance) package contains targeted implementations of these scores for the Poisson and the NegBin distributions, see, e.g., [`vignette("hhh4_spacetime")`](https://CRAN.R-project.org/web/packages/surveillance/vignettes/hhh4_spacetime.pdf) (Section 3.5) for a use case. For the future, it would be nice to just "import" such functionality from the dedicated **scoringRules** package.

**Comment by FK83** [comment]
Thanks for the kind note - glad you're finding the package useful!

Agreed that the DSS may be a useful addition - basically as a utility function for computing the mean and variance implied by a parametric fit. We (in fact, @aijordan) have just added the DSS for a few distributions, see e.g. the new function dss_pois. From a quick comparison, the scores seem to agree with the ones returned by the dss function from the **surveillance** package.

**Comment by WastlM** [comment]
Wow, thanks, that was fast. I'll test your implementation when working on the next version of **surveillance**.
