### ISSUE TITLE
implement and export general DSS formula

### ISSUE THREAD

**Issue by bastistician** [FK83/scoringRules#37]
All the DSS functions eventually need to compute something like

    (y - meanP)^2/varP + log(varP)

I think it would be cleaner to have a separate `dss` function which does just that, use it in the distribution-specific functions, and also export this basic function to enable the package user to compute the DSS for distributions not covered by the package.

**Comment by FK83** [comment]
Thanks - we'll think about that. 
 
The ensemble spread score (ESS) of Christensen et al (2015, [http://onlinelibrary.wiley.com/doi/10.1002/qj.2375/full](url)) which depends on the first three moments of the forecast distribution would probably be a worthwhile addition as well.

**Comment by FK83** [comment]
Sorry - I forgot to close this one. @slerch implemented the functions `dss_moments` and `ess_moments` way back in 2017, see 330a3244bcb83636312d6512b52d2c1368f6a96f. Thanks again for the hint!
