### ISSUE TITLE
Scoring rules for quantile and interval forecasts

### ISSUE THREAD

**Issue by dmi3kno** [FK83/scoringRules#41]
Hi, 
Thanks for the package! I wonder if Quantile and Interval Forecasts scoring rules (see [section 6 here](https://www.stat.washington.edu/raftery/Research/PDF/Gneiting2007jasa.pdf)) might be appropriate addition to the package?

**Comment by FK83** [comment]
Thanks - good point! We just added the functions `qs_quantiles` and `qs_sample` for the quantile score, as well as `ints_quantiles` and `ints_sample` for the interval score.
